spring:
  application:
    name: meu-hortifruti

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hortifruti_db}
    username: ${DB_USER:hortifruti_user}
    password: ${DB_PASSWORD:hortifruti_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        default_schema: public
        jdbc:
          time_zone: America/Sao_Paulo

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/hortifruti-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/hortifruti-realm/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO
    br.unip.ads.pim.meuhortifruti: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}

app:
  keycloak:
    realm: ${KEYCLOAK_REALM:hortifruti-realm}
    client-id: ${KEYCLOAK_CLIENT_ID:hortifruti-backend}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
